version: "3.9"
   
services:
    web:
        build: .
        container_name: web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/code
        ports:
          - "8000:8000"
        environment:
          - DEBUG=1
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
          - db
          - redis
    celery:
        build: .
        command: celery -A todo worker -l INFO -B
        volumes:
          - .:/code
        depends_on:
          - web
          - redis
    db:
        image: postgres
        container_name: db
        expose:
            - "5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
volumes:
    pgdata: